### PR TITLE
add support to add raw header

### PR DESCRIPTION
**Pull request by faiverson**
some scenarios we need to send case sensitive headers

### CODE REVIEW

**Comment by anlutro** [comment]
Interesting... if you need case-sensitive headers, maybe add a third argument `$preserveCase` to the existing header methods?

**Comment by faiverson** [comment]
I thought to change the method but I considered to try to not modify the existent code.
But yes, it is a possible solution too.

**Comment by anlutro** [comment]
As long as you only add a new argument without changing existing ones, it'll be fine. It's better than adding a new method with a bunch of code copy-pasted from the original method anyway.

Do you want to update your pull request with this changes (or create a new one if that's easier)?

**Comment by faiverson** [comment]
We will send another, thanks!

**Pull request closed without merging**
